=== pantonioletti/python_hacking/cpp/forecast_xml_build/Forecast.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT badDataCheck EMPTY>
<!ATTLIST badDataCheck
    elementID NMTOKEN #REQUIRED
    groupID   NMTOKEN #REQUIRED
    Threshold NMTOKEN #REQUIRED
    UUID      NMTOKEN #IMPLIED
>

<!ELEMENT defElement (elementGroup|linkedElement|projection|trend)*>
<!ATTLIST defElement
    elementID NMTOKEN #REQUIRED
    initValueType (0|1|2) #IMPLIED
    rank NMTOKEN #REQUIRED
    displayMode (1|2|3) #IMPLIED
    UUID      NMTOKEN #IMPLIED
>

<!ELEMENT definition (defElement+, badDataCheck?, patterns, trending?, applies-to+)>
<!ATTLIST definition
    displayName CDATA #REQUIRED
    id NMTOKEN #REQUIRED
    initDaysPrior NMTOKEN #REQUIRED
    timeIncrement NMTOKEN #REQUIRED
    UUID      NMTOKEN #IMPLIED
>

<!ELEMENT element (importDataOutliers?)>
<!ATTLIST element
    id                     NMTOKEN #REQUIRED
    defaultFormat          CDATA #REQUIRED
    displayName            CDATA #REQUIRED
    code                   NMTOKEN #IMPLIED
    dataForecastElementID  NMTOKEN #IMPLIED
    UUID                   NMTOKEN #IMPLIED
>

<!ELEMENT elementGroup (elementGroup*)>
<!ATTLIST elementGroup
    groupID NMTOKEN #REQUIRED
    rank NMTOKEN #IMPLIED
    linkSS_wfmXRef CDATA #IMPLIED
    linkSS_TypeAttrVal CDATA #IMPLIED
    ignoreGroupIfLinkedDeptMissing (Y|N) #IMPLIED 
    displayMode (1|2|3) #IMPLIED
    UUID      NMTOKEN #IMPLIED
>

<!ELEMENT group EMPTY>
<!ATTLIST group
    id NMTOKEN #REQUIRED
    displayName CDATA #REQUIRED
    defaultGroup NMTOKEN #IMPLIED
    code        NMTOKEN #IMPLIED
    UUID      NMTOKEN #IMPLIED
>

<!ELEMENT linkedElement EMPTY>
<!ATTLIST linkedElement
    elementID NMTOKEN #REQUIRED
    linkPercent NMTOKEN #IMPLIED
    UUID      NMTOKEN #IMPLIED
>

<!ELEMENT pattern_type EMPTY>
<!ATTLIST pattern_type
    default_periods NMTOKEN #IMPLIED
    default_weeks NMTOKEN #IMPLIED
    default_years NMTOKEN #IMPLIED
    id (1|2|3) #REQUIRED
    init_selected (Y|N) #IMPLIED
    UUID      NMTOKEN #IMPLIED
>

<!ELEMENT patterns (pattern_type+)>
<!ATTLIST patterns
    historyPeriods NMTOKEN #REQUIRED
    maxWeeks NMTOKEN #REQUIRED
    precision NMTOKEN #REQUIRED
    UUID      NMTOKEN #IMPLIED
>

<!ELEMENT projection EMPTY>
<!ATTLIST projection
    linkedProjElemID NMTOKEN #REQUIRED
    linkedProjTimeFrame (1|2) #REQUIRED
    lockedToProj NMTOKEN #REQUIRED
	linkType (1|2|3) #IMPLIED
    UUID      NMTOKEN #IMPLIED
>

<!ELEMENT root (definition+,element+,group+)>

<!ELEMENT trend EMPTY>
<!ATTLIST
    trend id (1|2|3) #REQUIRED
    timeFrame (1|2) #REQUIRED
    default_periods NMTOKEN #IMPLIED
    default_weeks NMTOKEN #IMPLIED
    default_years NMTOKEN #IMPLIED
    UUID      NMTOKEN #IMPLIED
>

<!ELEMENT trending (pattern_type+)>
<!ATTLIST trending
    historyPeriods NMTOKEN #REQUIRED
    maxWeeks NMTOKEN #REQUIRED
    precision NMTOKEN #REQUIRED
    UUID      NMTOKEN #IMPLIED
>

<!ELEMENT applies-to (org+)>
<!ATTLIST applies-to
    UUID      NMTOKEN #IMPLIED
>

<!ELEMENT org EMPTY>
<!ATTLIST org
    id NMTOKEN #IMPLIED
    level NMTOKEN #IMPLIED
    attr_id NMTOKEN #IMPLIED
    applicable (Y|N) #IMPLIED
    UUID      NMTOKEN #IMPLIED
>

<!ELEMENT importDataOutliers EMPTY>
<!ATTLIST importDataOutliers
    detect (Y|N) #IMPLIED
    negativesAreOutliers (Y|N) #IMPLIED
    ignoreNConsecutiveZeros NMTOKEN #IMPLIED
    standardDeviations CDATA #REQUIRED
    correctionMode (1|2|3) #IMPLIED
    trackCorrections (Y|N) #IMPLIED
    minimumValues NMTOKEN #IMPLIED
    UUID NMTOKEN #IMPLIED
>

<!ENTITY INIT_TYPE_PATTERN  "0" >
<!ENTITY INIT_TYPE_PROJECTION  "1" >
<!ENTITY INIT_TYPE_TREND  "2" >

<!ENTITY LINK_TIME_FRAME_DAY  "1" >
<!ENTITY LINK_TIME_FRAME_WEEK  "2" >

<!ENTITY PATTERN_TYPE_LAST_X_WEEKS  "1" >
<!ENTITY PATTERN_TYPE_SAME_WEEK_LAST_X_YEARS  "2" >
<!ENTITY PATTERN_TYPE_WPY  "3" >

<!ENTITY PROJECTION_LINK_TYPE_STORE  "1" >
<!ENTITY PROJECTION_LINK_TYPE_HIGHEST_DEPT  "2" >
<!ENTITY PROJECTION_LINK_TYPE_LOWEST_DEPT  "3" >

<!ENTITY OUTLIER_CORRECTION_MODE_SET_TO_STANDARD_DEVIATION "1" >
<!ENTITY OUTLIER_CORRECTION_MODE_SET_TO_NEIGHBOR_AVERAGE "2" >
<!ENTITY OUTLIER_CORRECTION_MODE_TRACKING_ONLY "3" >

<!ENTITY DISPLAY_MODE_NORMAL "1" >
<!ENTITY DISPLAY_MODE_READ_ONLY "2" >
<!ENTITY DISPLAY_MODE_HIDDEN "3" >

=== pantonioletti/python_hacking/cpp/forecast_xml_build/Forecast.xml
<?xml version="1.0" encoding="ISO_8859-1"?>
<!DOCTYPE root SYSTEM "Forecast.dtd">
<root>
<definition id="1" displayName="15MIN" initDaysPrior="7" timeIncrement="15" >
    <defElement elementID="1" initValueType="&INIT_TYPE_TREND;" rank="1" >
        <projection linkedProjElemID="1" linkedProjTimeFrame="&LINK_TIME_FRAME_DAY;" lockedToProj="N" />
        <linkedElement elementID="50" linkPercent="100" />
        <linkedElement elementID="51" linkPercent="100" />
        <linkedElement elementID="52" linkPercent="100" />
        <linkedElement elementID="53" linkPercent="100" />
        <linkedElement elementID="54" linkPercent="100" />
        <linkedElement elementID="55" linkPercent="100" />
        <linkedElement elementID="57" linkPercent="100" />
        <linkedElement elementID="58" linkPercent="100" />
        <elementGroup groupID="1" rank="1" />
    </defElement>
    <defElement elementID="50" initValueType="&INIT_TYPE_PATTERN;" rank="2" >
        <elementGroup groupID="1" rank="1" />
    </defElement>
    <defElement elementID="51" initValueType="&INIT_TYPE_PATTERN;" rank="3" >
        <elementGroup groupID="1" rank="1" />
    </defElement>
    <defElement elementID="52" initValueType="&INIT_TYPE_PATTERN;" rank="4" >
        <elementGroup groupID="1" rank="1" />
    </defElement>
    <defElement elementID="53" initValueType="&INIT_TYPE_PATTERN;" rank="5" >
        <elementGroup groupID="1" rank="1" />
    </defElement>
    <defElement elementID="54" initValueType="&INIT_TYPE_PATTERN;" rank="6" >
        <elementGroup groupID="1" rank="1" />
    </defElement>
    <defElement elementID="55" initValueType="&INIT_TYPE_PATTERN;" rank="7" >
        <elementGroup groupID="50" rank="1" />
        <elementGroup groupID="51" rank="2" />
        <elementGroup groupID="52" rank="3" />
        <elementGroup groupID="53" rank="4" />
        <elementGroup groupID="54" rank="5" />
        <elementGroup groupID="55" rank="6" />
        <elementGroup groupID="56" rank="7" />
        <elementGroup groupID="57" rank="8" />
        <elementGroup groupID="58" rank="9" />
        <elementGroup groupID="59" rank="10" />
        <elementGroup groupID="60" rank="11" />
        <elementGroup groupID="61" rank="12" />
        <elementGroup groupID="62" rank="13" />
        <elementGroup groupID="63" rank="14" />
        <elementGroup groupID="64" rank="15" />
        <elementGroup groupID="65" rank="16" />
        <elementGroup groupID="66" rank="17" />
        <elementGroup groupID="67" rank="18" />
        <elementGroup groupID="68" rank="19" />
        <elementGroup groupID="69" rank="20" />
        <elementGroup groupID="70" rank="21" />
        <elementGroup groupID="71" rank="22" />
        <elementGroup groupID="72" rank="23" />
        <elementGroup groupID="73" rank="24" />
        <elementGroup groupID="74" rank="25" />
        <elementGroup groupID="75" rank="26" />
        <elementGroup groupID="76" rank="27" />
        <elementGroup groupID="77" rank="28" />
        <elementGroup groupID="78" rank="29" />
        <elementGroup groupID="79" rank="30" />
        <elementGroup groupID="80" rank="31" />
        <elementGroup groupID="81" rank="32" />
        <elementGroup groupID="82" rank="33" />
        <elementGroup groupID="83" rank="34" />
        <elementGroup groupID="84" rank="35" />
        <elementGroup groupID="85" rank="36" />
        <elementGroup groupID="86" rank="37" />
        <elementGroup groupID="87" rank="38" />
        <elementGroup groupID="88" rank="39" />
        <elementGroup groupID="89" rank="40" />
        <elementGroup groupID="90" rank="41" />
        <elementGroup groupID="91" rank="42" />
        <elementGroup groupID="92" rank="43" />
        <elementGroup groupID="93" rank="44" />
        <elementGroup groupID="94" rank="45" />
        <elementGroup groupID="95" rank="46" />
        <elementGroup groupID="96" rank="47" />
        <elementGroup groupID="97" rank="48" />
        <elementGroup groupID="98" rank="49" />
        <elementGroup groupID="99" rank="50" />
        <elementGroup groupID="100" rank="51" />
        <elementGroup groupID="101" rank="52" />
        <elementGroup groupID="102" rank="53" />
        <elementGroup groupID="103" rank="54" />
        <elementGroup groupID="104" rank="55" />
        <elementGroup groupID="105" rank="56" />
        <elementGroup groupID="106" rank="57" />
        <elementGroup groupID="107" rank="58" />
        <elementGroup groupID="108" rank="59" />
        <elementGroup groupID="109" rank="60" />
        <elementGroup groupID="110" rank="61" />
        <elementGroup groupID="111" rank="62" />
        <elementGroup groupID="112" rank="63" />
        <elementGroup groupID="113" rank="64" />
        <elementGroup groupID="114" rank="65" />
        <elementGroup groupID="115" rank="66" />
        <elementGroup groupID="116" rank="67" />
        <elementGroup groupID="117" rank="68" />
        <elementGroup groupID="118" rank="69" />
        <elementGroup groupID="119" rank="70" />
        <elementGroup groupID="120" rank="71" />
        <elementGroup groupID="121" rank="72" />
        <elementGroup groupID="122" rank="73" />
        <elementGroup groupID="123" rank="74" />
        <elementGroup groupID="124" rank="75" />
        <elementGroup groupID="125" rank="76" />
        <elementGroup groupID="126" rank="77" />
        <elementGroup groupID="127" rank="78" />
        <elementGroup groupID="128" rank="79" />
        <elementGroup groupID="129" rank="80" />
        <elementGroup groupID="130" rank="81" />
        <elementGroup groupID="131" rank="82" />
        <elementGroup groupID="132" rank="83" />
        <elementGroup groupID="133" rank="84" />
        <elementGroup groupID="134" rank="85" />
        <elementGroup groupID="135" rank="86" />
        <elementGroup groupID="136" rank="87" />
        <elementGroup groupID="137" rank="88" />
        <elementGroup groupID="138" rank="89" />
    </defElement>
    <defElement elementID="57" initValueType="&INIT_TYPE_PATTERN;" rank="8" >
        <elementGroup groupID="1" rank="1" />
    </defElement>
    <defElement elementID="58" initValueType="&INIT_TYPE_PATTERN;" rank="9" >
        <elementGroup groupID="50" rank="1" />
        <elementGroup groupID="51" rank="2" />
        <elementGroup groupID="52" rank="3" />
        <elementGroup groupID="53" rank="4" />
        <elementGroup groupID="54" rank="5" />
        <elementGroup groupID="55" rank="6" />
        <elementGroup groupID="56" rank="7" />
        <elementGroup groupID="57" rank="8" />
        <elementGroup groupID="58" rank="9" />
        <elementGroup groupID="59" rank="10" />
        <elementGroup groupID="60" rank="11" />
        <elementGroup groupID="61" rank="12" />
        <elementGroup groupID="62" rank="13" />
        <elementGroup groupID="63" rank="14" />
        <elementGroup groupID="64" rank="15" />
        <elementGroup groupID="65" rank="16" />
        <elementGroup groupID="66" rank="17" />
        <elementGroup groupID="67" rank="18" />
        <elementGroup groupID="68" rank="19" />
        <elementGroup groupID="69" rank="20" />
        <elementGroup groupID="70" rank="21" />
        <elementGroup groupID="71" rank="22" />
        <elementGroup groupID="72" rank="23" />
        <elementGroup groupID="73" rank="24" />
        <elementGroup groupID="74" rank="25" />
        <elementGroup groupID="75" rank="26" />
        <elementGroup groupID="76" rank="27" />
        <elementGroup groupID="77" rank="28" />
        <elementGroup groupID="78" rank="29" />
        <elementGroup groupID="79" rank="30" />
        <elementGroup groupID="80" rank="31" />
        <elementGroup groupID="81" rank="32" />
        <elementGroup groupID="82" rank="33" />
        <elementGroup groupID="83" rank="34" />
        <elementGroup groupID="84" rank="35" />
        <elementGroup groupID="85" rank="36" />
        <elementGroup groupID="86" rank="37" />
        <elementGroup groupID="87" rank="38" />
        <elementGroup groupID="88" rank="39" />
        <elementGroup groupID="89" rank="40" />
        <elementGroup groupID="90" rank="41" />
        <elementGroup groupID="91" rank="42" />
        <elementGroup groupID="92" rank="43" />
        <elementGroup groupID="93" rank="44" />
        <elementGroup groupID="94" rank="45" />
        <elementGroup groupID="95" rank="46" />
        <elementGroup groupID="96" rank="47" />
        <elementGroup groupID="97" rank="48" />
        <elementGroup groupID="98" rank="49" />
        <elementGroup groupID="99" rank="50" />
        <elementGroup groupID="100" rank="51" />
        <elementGroup groupID="101" rank="52" />
        <elementGroup groupID="102" rank="53" />
        <elementGroup groupID="103" rank="54" />
        <elementGroup groupID="104" rank="55" />
        <elementGroup groupID="105" rank="56" />
        <elementGroup groupID="106" rank="57" />
        <elementGroup groupID="107" rank="58" />
        <elementGroup groupID="108" rank="59" />
        <elementGroup groupID="109" rank="60" />
        <elementGroup groupID="110" rank="61" />
        <elementGroup groupID="111" rank="62" />
        <elementGroup groupID="112" rank="63" />
        <elementGroup groupID="113" rank="64" />
        <elementGroup groupID="114" rank="65" />
        <elementGroup groupID="115" rank="66" />
        <elementGroup groupID="116" rank="67" />
        <elementGroup groupID="117" rank="68" />
        <elementGroup groupID="118" rank="69" />
        <elementGroup groupID="119" rank="70" />
        <elementGroup groupID="120" rank="71" />
        <elementGroup groupID="121" rank="72" />
        <elementGroup groupID="122" rank="73" />
        <elementGroup groupID="123" rank="74" />
